spring.application.name=TaskFlow

# JWT
jwt.key=${JWT_KEY}
jwt.expiration=${JWT_EXPIRATION:3600000}
jwt.invitacion.expiration=${JWT_INVITATION_EXPIRATION:604800000}

# MongoDB Atlas
spring.data.mongodb.uri=${MONGODB_URI}

# Mail (Gmail SMTP)
spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.base-url=${APP_BASE_URL:http://localhost:8080}
